services:
  frontend:
    build:
      context: .
    volumes:
      - .:/app:rw,delegated
    tty: true
    networks:
      - agenda_api
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`agenda-react.romdev.ovh`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    command: npm run preview

networks:
  proxy:
    external: true
  agenda_api:
    internal: true